const $=id=>document.getElementById(id),state={page:1,search:""},date=new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"});
async function api(path,options){const r=await fetch(path,{headers:{Accept:"application/json",...(options?.headers||{})},...options});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).detail||`Request failed (${r.status})`);return r.json()}
function esc(value){const e=document.createElement("span");e.textContent=value??"";return e.innerHTML}
function chart(daily){const counts=new Map(daily.map(x=>[x.date,x.runs])),days=Array.from({length:14},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-13+i);return{d,key:d.toISOString().slice(0,10)}}),max=Math.max(...days.map(x=>counts.get(x.key)||0),1);$("chart").replaceChildren(...days.map(x=>{const runs=counts.get(x.key)||0,h=runs?Math.max(runs/max*100,10):2,e=document.createElement("div");e.className="bar";e.style.setProperty("--h",`${h}%`);e.innerHTML=`<b>${runs}</b><div style="height:${h}%"></div><small>${x.d.toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small>`;return e}));$("recent").textContent=days.reduce((n,x)=>n+(counts.get(x.key)||0),0)}
function row(item){const tr=document.createElement("tr");tr.innerHTML=`<td><strong>${date.format(new Date(item.created_at))}</strong><small>● Completed</small></td><td><strong>${esc(item.ticket_id)}</strong><small>${esc(item.subject)}</small></td><td><div class="output">${esc(item.recommended_response)}</div></td><td>${esc(item.workflow_id)}</td><td><button>View</button></td>`;tr.querySelector("button").onclick=()=>detail(item.case_id);return tr}
async function load(){const q=new URLSearchParams({page:state.page,page_size:10});if(state.search)q.set("search",state.search);const data=await api(`/cases?${q}`);$("rows").replaceChildren(...(data.items.length?data.items.map(row):[Object.assign(document.createElement("tr"),{innerHTML:'<td colspan="5">No matching cases.</td>'})]));$("total").textContent=data.total;$("pageinfo").textContent=`${data.total?((data.page-1)*data.page_size+1):0}–${Math.min(data.page*data.page_size,data.total)} of ${data.total} cases`;$("page").textContent=`Page ${data.page}`;$("prev").disabled=data.page===1;$("next").disabled=data.page*data.page_size>=data.total;if(!state.search&&data.items[0]){$("latest").textContent=data.items[0].classification;$("latestdetail").textContent=data.items[0].priority}}
async function detail(id){const x=await api(`/cases/${id}`);$("title").textContent=`${x.ticket_id} · ${x.classification}`;$("input").textContent=`${x.subject}\n\n${x.classification_reason}`;$("output").textContent=x.recommended_response;$("detail").showModal()}
async function init(){const[c,t]=await Promise.all([api("/ui/config"),api("/case-history/trend")]);const name=new URLSearchParams(location.search).get("user")||c.display_name||"Local administrator";$("name").textContent=name;$("initial").textContent=name[0].toUpperCase();$("traces").href=c.langfuse_url;chart(t.daily);await load()}
$("form").onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$("status").textContent="Running support workflow…";try{await api("/support/triage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticket_id:$("ticket").value,subject:$("subject").value,message:$("message").value,customer_tier:$("tier").value,user_id:$("name").textContent,conversation_id:`support-ui-${Date.now()}`})});state.page=1;$("status").textContent="Workflow complete — history refreshed.";await init()}catch(x){$("status").textContent=x.message}finally{b.disabled=false}};let timer;$("search").oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=e.target.value;state.page=1;load()},250)};$("refresh").onclick=()=>init();$("prev").onclick=()=>{state.page--;load()};$("next").onclick=()=>{state.page++;load()};$("close").onclick=()=>$("detail").close();$("theme").onclick=()=>{const d=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=d;localStorage.supportTheme=d;$("theme").textContent=d==="dark"?"☀ Light":"☾ Dark"};document.documentElement.dataset.theme=localStorage.supportTheme||"light";init().catch(x=>$("rows").innerHTML=`<tr><td colspan="5">${esc(x.message)}</td></tr>`);
